---
- name: "Nextcloud playbook"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - docker_container:
        restart: yes
        restart_policy: always
        name: nextcloud
        image: ownyourbits/nextcloudpi
        pull: yes
        volumes:
          - 'ncdata:/data'
        ports:
          - '8888:80'
          - '440:443'
          - '9999:4443'
